print("^2 ================================================================ ")
print("")
print("")
print("^1\t\t   RUBY CORE ALPHA")
print("^3\t      Tout est charger sans erreur!")
print("")
print("\t\t^1Crée par Rubylium#3694")
print("")
print("^2 ================================================================")